### PR TITLE
Dig profiler

### PR DESCRIPTION
**Pull request by katkad**
test PR, to see if dig is missing

edit: also do not shorten error message so we can get more than:
"Error inserting attack event into main database: (OperationalError) table events has"

### CODE REVIEW

**Comment by katkad** [comment]
@glaslos you were right with https://github.com/mushorg/glastopf/pull/237#issuecomment-129427774
this passes

**Comment by katkad** [comment]
ping ?

**Comment by glaslos** [comment]
@katkad can you briefly describe this feature?

**Comment by glaslos** [comment]
There are also some conflicts from the other pull requests I merged.

**Comment by katkad** [comment]
hi, it is https://github.com/mushorg/glastopf/pull/237 but tests for this PR pass

**Comment by katkad** [comment]
rebased. but I don't understand errors from Travis

**Comment by glaslos** [comment]
Ah, the test failed because of some changes I did in my backend. Should run through fine now.

**Comment by glaslos** [comment]
@katkad test passed. Feel free to squash and merge.

**Comment by katkad** [comment]
finaly in master https://github.com/mushorg/glastopf/commit/f1842ba1fe99243c957ad715a50bf240a7a65f28

**Pull request closed without merging**
